
spring:
  mail: 
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import:
    - optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DBNAME}?currentSchema=${PG_SCHEMA}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  servlet:
    multipart:
      enabled: true 
      max-file-size: 2MB
      max-request-size: 5MB
---
app:
  token:
    secret: ${APP_SECRET}
    issuer: ${APP_ISSUER}
  email:
    from: ${EMAIL_FROM}